# Generated by Django 4.2.24 on 2025-10-06 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120, verbose_name="Título")),
                ("slug", models.SlugField(unique=True)),
                ("summary", models.TextField(verbose_name="Descrição")),
                ("order", models.PositiveIntegerField(default=0)),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Serviço",
                "verbose_name_plural": "Serviços",
                "ordering": ("order", "title"),
            },
        ),
        migrations.CreateModel(
            name="SiteTheme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="Padrão", max_length=60, verbose_name="Nome da paleta"
                    ),
                ),
                (
                    "color1",
                    models.CharField(
                        default="#0b1020", max_length=7, verbose_name="Primária"
                    ),
                ),
                (
                    "color2",
                    models.CharField(
                        default="#6aa3ff", max_length=7, verbose_name="Secundária"
                    ),
                ),
                (
                    "color3",
                    models.CharField(
                        default="#10bfae", max_length=7, verbose_name="Acento"
                    ),
                ),
                (
                    "color4",
                    models.CharField(
                        default="#e8eefc", max_length=7, verbose_name="Texto"
                    ),
                ),
                (
                    "color5",
                    models.CharField(
                        default="#9fb3d1", max_length=7, verbose_name="Muted"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Paleta de cores",
                "verbose_name_plural": "Paletas de cores",
            },
        ),
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "site_name",
                    models.CharField(
                        default="Convexa", max_length=120, verbose_name="Nome do site"
                    ),
                ),
                (
                    "domain",
                    models.CharField(
                        default="convexa.com.br", max_length=120, verbose_name="Domínio"
                    ),
                ),
                (
                    "city_state",
                    models.CharField(
                        default="Rio de Janeiro - RJ",
                        max_length=120,
                        verbose_name="Local",
                    ),
                ),
                (
                    "founded",
                    models.DateField(blank=True, null=True, verbose_name="Fundação"),
                ),
                ("about", models.TextField(blank=True, verbose_name="Sobre")),
                (
                    "use_gradient_logo_text",
                    models.BooleanField(
                        default=True, verbose_name="Texto da marca com gradiente"
                    ),
                ),
                (
                    "youtube_url",
                    models.URLField(blank=True, verbose_name="Canal do YouTube"),
                ),
                (
                    "theme",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.sitetheme",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuração do site",
                "verbose_name_plural": "Configurações do site",
            },
        ),
    ]
