# Generated by Django 4.2.24 on 2025-10-06 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_init_core"),
    ]

    operations = [
        migrations.CreateModel(
            name="YouTubeVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150, verbose_name="Título")),
                (
                    "video_id",
                    models.CharField(
                        help_text="Ex.: dQw4w9WgXcQ",
                        max_length=20,
                        verbose_name="ID do vídeo (YouTube)",
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Publicado em"
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Vídeo do YouTube",
                "verbose_name_plural": "Vídeos do YouTube",
                "ordering": ("order", "-published_at", "title"),
            },
        ),
    ]
