# Generated by Django 4.2.24 on 2025-10-06 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_youtube_videos"),
    ]

    operations = [
        migrations.AddField(
            model_name="youtubevideo",
            name="channel_title",
            field=models.CharField(blank=True, max_length=150, verbose_name="Canal"),
        ),
        migrations.AddField(
            model_name="youtubevideo",
            name="duration",
            field=models.CharField(
                blank=True, max_length=32, verbose_name="Duração (ISO8601)"
            ),
        ),
        migrations.AddField(
            model_name="youtubevideo",
            name="last_refreshed",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Última atualização"
            ),
        ),
        migrations.AddField(
            model_name="youtubevideo",
            name="optimized_summary",
            field=models.TextField(blank=True, verbose_name="Resumo otimizado (IA)"),
        ),
        migrations.AddField(
            model_name="youtubevideo",
            name="original_description",
            field=models.TextField(blank=True, verbose_name="Descrição original"),
        ),
        migrations.AddField(
            model_name="youtubevideo",
            name="slug",
            field=models.SlugField(blank=True, max_length=170, verbose_name="Slug"),
        ),
    ]
