# Generated by Django 4.2.24 on 2025-10-06 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_videos_meta"),
    ]

    operations = [
        migrations.CreateModel(
            name="IntegrationKeys",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "openai_api_key",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="OpenAI API Key"
                    ),
                ),
                (
                    "youtube_api_key",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="YouTube API Key"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Chaves de Integração",
                "verbose_name_plural": "Chaves de Integração",
            },
        ),
    ]
