# Generated by Django 4.2.24 on 2025-10-01 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('external_url', models.CharField(blank=True, max_length=200, verbose_name='Link externo (se não houver página)')),
                ('order', models.IntegerField(default=0, verbose_name='Ordem')),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.page', verbose_name='Página de destino')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='menu_manager.menuitem', verbose_name='Menu Pai (para submenus)')),
            ],
            options={
                'verbose_name': 'Item de Menu',
                'verbose_name_plural': 'Itens de Menu',
                'ordering': ['order'],
            },
        ),
    ]
