# Generated by Django 4.2.24 on 2025-10-01 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='open_in_new_tab',
            field=models.BooleanField(default=False, verbose_name='Abrir em nova aba?'),
        ),
    ]
