# Generated by Django 4.2.24 on 2025-10-01 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='URL (atalho)')),
                ('author', models.CharField(max_length=100, verbose_name='Autor')),
                ('content', models.TextField(verbose_name='Conteúdo do Artigo')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='blog_covers/', verbose_name='Imagem de Capa')),
                ('youtube_video_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='ID do Vídeo no YouTube (Opcional)')),
                ('publication_date', models.DateTimeField(auto_now_add=True, verbose_name='Data de Publicação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Modificação')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'ordering': ['-publication_date'],
            },
        ),
    ]
