# Generated by Django 4.2.24 on 2025-10-01 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='URL (atalho)')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('image', models.ImageField(upload_to='portfolio_images/', verbose_name='Imagem do Projeto')),
                ('technologies', models.CharField(max_length=200, verbose_name='Tecnologias Usadas')),
                ('project_url', models.URLField(blank=True, verbose_name='Link do Projeto')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
            ],
            options={
                'verbose_name': 'Projeto',
                'verbose_name_plural': 'Projetos',
                'ordering': ['-created_at'],
            },
        ),
    ]
